"""Modified table resource1

Revision ID: ea3c6df4e9fa
Revises: ffe93efeb770
Create Date: 2023-04-01 21:28:43.245118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3c6df4e9fa'
down_revision = 'ffe93efeb770'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_resource1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_resource1_id'), 'example_resource1', ['id'], unique=False)
    op.create_index(op.f('ix_example_resource1_name'), 'example_resource1', ['name'], unique=True)
    op.drop_index('ix_taxes_email', table_name='taxes')
    op.drop_index('ix_taxes_id', table_name='taxes')
    op.drop_table('taxes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary_income', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salary_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='taxes_pkey')
    )
    op.create_index('ix_taxes_id', 'taxes', ['id'], unique=False)
    op.create_index('ix_taxes_email', 'taxes', ['email'], unique=False)
    op.drop_index(op.f('ix_example_resource1_name'), table_name='example_resource1')
    op.drop_index(op.f('ix_example_resource1_id'), table_name='example_resource1')
    op.drop_table('example_resource1')
    # ### end Alembic commands ###
